import { useEffect, useState } from "react";
import { Activity, Ban, Check, FileQuestion, Flag, LayoutDashboard, LockKeyhole, MessageSquareWarning, Shield, Sparkles, Users, X } from "lucide-react";
import { quizRealmApi } from "@/lib/quizrealm";
import { CornerFiligree, HeraldicAvatar, RealmCrest, RuneDivider, TerritoryMapSvg } from "@/components/MedievalSvg";

type Section = "overview" | "users" | "reports" | "questions";
const nav: Array<[Section, string, typeof LayoutDashboard]> = [["overview", "Registrul de război", LayoutDashboard], ["users", "Purtători de stindard", Users], ["reports", "Sesizări", MessageSquareWarning], ["questions", "Codexul de lore", FileQuestion]];

export default function Admin() {
  const [section, setSection] = useState<Section>("overview"); const [dashboard, setDashboard] = useState<any>(null); const [users, setUsers] = useState<any[]>([]); const [reports, setReports] = useState<any[]>([]); const [questions, setQuestions] = useState<any[]>([]); const [notice, setNotice] = useState(""); const [loadError, setLoadError] = useState(""); const [stats, setStats] = useState<any>(null);
  const refresh = () => { setLoadError(""); Promise.all([quizRealmApi.adminDashboard(), quizRealmApi.adminUsers(), quizRealmApi.adminChatReports(), quizRealmApi.adminQuestions(), quizRealmApi.adminQuestionStats()]).then(([dash, userList, reportList, questionList, nextStats]) => { setDashboard(dash); if (Array.isArray(userList)) setUsers(userList); if (Array.isArray(reportList)) setReports(reportList); if (Array.isArray(questionList)) setQuestions(questionList); setStats(nextStats); }).catch(error => setLoadError(error instanceof Error ? error.message : "API-ul consiliului e indisponibil")); };
  useEffect(refresh, []);
  const action = async (label: string, call: () => Promise<unknown>) => { try { await call(); setNotice(`${label} · sigilat`); refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : `${label} · indisponibil`); } };
  return <div className="realm-surface min-h-[calc(100vh-72px)]"><div className="mx-auto flex max-w-[1480px] px-5 py-7 lg:px-10"><aside className="engraved-frame hidden w-60 shrink-0 self-start overflow-hidden rounded-2xl p-5 lg:block"><div className="mb-9 flex items-center gap-3"><RealmCrest className="h-11 w-11 text-[#e3c36a]" /><div><div className="eyebrow">Camera consiliului</div><div className="mt-1 text-sm font-bold text-[#f7e7b0]">Controlul tărâmului</div></div></div><div className="space-y-1">{nav.map(([id, label, Icon]) => <button key={id} onClick={() => setSection(id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold ${section === id ? "bg-[#e0ba58]/12 text-[#f5dda0]" : "text-[#aaa0ad] hover:bg-white/5 hover:text-white"}`}><Icon size={17} />{label}</button>)}</div><div className="relative mt-12 overflow-hidden rounded-xl border border-[#8d6bda]/25 bg-[#8d6bda]/8 p-4"><CornerFiligree className="absolute -right-7 -top-7 h-18 w-18 text-[#8d6bda]" /><div className="relative flex items-center gap-2 text-xs font-bold text-[#d8ccff]"><Activity size={14} /> Starea turnului de veghe</div><div className="relative mt-3 flex items-center gap-2 text-xs text-[#b4a9bb]"><span className="h-2 w-2 rounded-full bg-[#2bc7b4]" /> {dashboard ? "Metrici live primite" : "Se așteaptă API-ul consiliului"}</div></div></aside>
    <main className="min-w-0 flex-1 py-1 lg:pl-8"><div className="relative overflow-hidden rounded-2xl"><TerritoryMapSvg className="pointer-events-none absolute -right-44 -top-48 h-[520px] w-[860px] opacity-[.1]" /><div className="relative mb-7 flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">Camera consiliului / {section}</div><h1 className="mt-2 font-display text-3xl text-[#f7e7b0]">{nav.find(item => item[0] === section)?.[1]}</h1></div><div className="rune-chip flex items-center gap-2 rounded-full px-3 py-2 text-xs text-[#f5dda0]"><LockKeyhole size={13} />{dashboard ? `${dashboard.activeUsers ?? 0} semnale active` : "Sigiliu de admin verificat"}</div></div></div><RuneDivider className="mb-5 h-7 w-full text-[#e0ba58]" />
      {loadError && <Banner color="rose" text={loadError} onClose={() => setLoadError("")} />}{notice && <Banner color="gold" text={notice} onClose={() => setNotice("")} />}
      {section === "overview" && <Overview dashboard={dashboard} onSelect={setSection} />}{section === "users" && <UsersPanel users={users} action={action} />}{section === "reports" && <ReportsPanel reports={reports} action={action} />}{section === "questions" && <QuestionsPanel questions={questions} stats={stats} action={action} />}
    </main>
  </div></div>;
}

function Banner({ color, text, onClose }: { color: "gold" | "rose"; text: string; onClose: () => void }) { const css = color === "gold" ? "border-[#e0ba58]/35 bg-[#e0ba58]/10 text-[#f5dda0]" : "border-[#e57a87]/35 bg-[#e57a87]/10 text-[#ffb5bf]"; return <div className={`mb-5 flex items-center justify-between border px-4 py-3 text-sm ${css}`}>{text}<button onClick={onClose}><X size={15} /></button></div>; }
function Overview({ dashboard, onSelect }: { dashboard: any; onSelect: (section: Section) => void }) { const cards = [["Semnale active", dashboard?.activeUsers ?? "—", Users, "#2bc7b4"], ["Bătălii / 24h", dashboard?.matchesPerDay ?? "—", Activity, "#e0ba58"], ["Relicve deblocate", dashboard?.achievementsUnlocked ?? "—", Sparkles, "#8d6bda"], ["Sesizări", dashboard?.pendingReports ?? "—", Flag, "#e57a87"]] as const; return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, color]) => <div key={label} className="engraved-frame relative overflow-hidden rounded-2xl p-5"><CornerFiligree className="absolute -right-7 -top-7 h-20 w-20" style={{ color }} /><div className="relative flex items-center justify-between"><span className="text-xs text-[#aaa0ad]">{label}</span><Icon size={17} style={{ color }} /></div><div className="relative mt-4 font-display text-3xl text-[#f7e7b0]">{value}</div><div className="relative mt-2 text-xs text-[#b7f0e6]">Verificat de consiliu</div></div>)}</div><div className="mt-5 grid gap-5 md:grid-cols-3">{[["users", "Purtători de stindard", "Acordă sau retrage accesul, rupe sesiunile blestemate.", Users, "#e0ba58"], ["reports", "Sesizări", "Analizează plângerile din tărâm și dă verdictul.", MessageSquareWarning, "#e57a87"], ["questions", "Codexul de lore", "Aprobă întrebări noi pentru arhiva tărâmului.", FileQuestion, "#8d6bda"]].map(([id, title, copy, Icon, color]: any) => <button key={id} onClick={() => onSelect(id)} className="panel panel-hover relative overflow-hidden rounded-2xl p-6 text-left"><CornerFiligree className="absolute -right-7 -top-7 h-20 w-20" style={{ color }} /><Icon className="relative" style={{ color }} /><h2 className="relative mt-4 text-lg font-bold text-[#f7e7b0]">{title}</h2><p className="relative mt-2 text-sm text-[#aaa0ad]">{copy}</p></button>)}</div></>; }
function UsersPanel({ users, action }: { users: any[]; action: (label: string, fn: () => Promise<unknown>) => void }) { return <div className="engraved-frame overflow-hidden rounded-2xl"><header className="border-b border-[#e0ba58]/15 p-5"><div className="eyebrow">Operațiuni pe stindarde</div><h2 className="mt-2 text-lg font-bold text-[#f7e7b0]">Purtători · {users.length}</h2></header><div className="divide-y divide-white/6">{users.map((user, index) => <div key={user.id || user.username} className="flex flex-wrap items-center gap-3 p-5"><div className="relative h-10 w-10 overflow-hidden rounded-full"><HeraldicAvatar variant={(["astromancer", "oracle", "runeknight"] as const)[index % 3]} className="h-full w-full" /></div><div className="min-w-[180px] flex-1"><div className="text-sm font-bold text-[#eee4ca]">{user.username}</div><div className="text-xs text-[#8f8494]">{user.email}</div></div><span className="text-xs text-[#cfc2d3]">{user.role}</span><span className="text-sm text-[#e3c36a]">{user.eloRating}</span><button onClick={() => user.bannedAt ? action("Interdicție ridicată", () => quizRealmApi.adminUnbanUser(user.id)) : action("Stindard alungat", () => quizRealmApi.adminBanUser(user.id))} disabled={!user.id} className="rounded-lg bg-[#e57a87]/10 px-3 py-2 text-xs text-[#ffb5bf] disabled:opacity-40">{user.bannedAt ? "Ridică interdicția" : "Alungă"}</button><button onClick={() => action("Sesiuni rupte", () => quizRealmApi.adminRevokeSessions(user.id))} disabled={!user.id} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-[#cbc1cf] disabled:opacity-40">Rupe sesiunile</button></div>)}</div></div>; }
function ReportsPanel({ reports, action }: { reports: any[]; action: (label: string, fn: () => Promise<unknown>) => void }) { return <div className="engraved-frame overflow-hidden rounded-2xl"><header className="border-b border-[#e0ba58]/15 p-5"><div className="eyebrow">Operațiuni de veghe</div><h2 className="mt-2 text-lg font-bold text-[#f7e7b0]">Sesizări deschise · {reports.length}</h2></header><div className="divide-y divide-white/6">{reports.map(report => <div key={report.id} className="flex flex-wrap items-center gap-4 p-5"><Flag size={17} className="text-[#ff9baa]" /><div className="min-w-[190px] flex-1"><div className="text-sm font-bold text-[#eee4ca]">{report.id}</div><div className="mt-1 text-xs text-[#8f8494]">{report.scope} · {report.reason}</div></div><button onClick={() => action("Sesizare respinsă", () => quizRealmApi.adminResolveChatReport(report.id, "DISMISSED"))} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-[#cbc1cf]">Respinge</button><button onClick={() => action("Stindard amuțit", () => quizRealmApi.adminResolveChatReport(report.id, "MUTED"))} className="rounded-lg bg-[#e0ba58]/10 px-3 py-2 text-xs text-[#f5dda0]">Amuțește</button>{report.reportedUserId && <button onClick={() => action("Sigiliu de umbră aplicat", () => quizRealmApi.adminShadowBan(report.reportedUserId, 60))} className="rounded-lg bg-[#8d6bda]/12 px-3 py-2 text-xs text-[#d8ccff]">Sigiliu de umbră</button>}</div>)}</div></div>; }
function QuestionsPanel({ questions, stats, action }: { questions: any[]; stats: any; action: (label: string, fn: () => Promise<unknown>) => void }) { return <div className="engraved-frame rounded-2xl p-6"><div className="flex items-center justify-between"><div><div className="eyebrow">Lore din comunitate</div><h2 className="mt-2 text-lg font-bold text-[#f7e7b0]">Revizuire codex · {questions.length}</h2></div><FileQuestion className="text-[#d8ccff]" /></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs">{[["Categorii", stats?.categories, "#e0ba58"], ["Aprobate", stats?.approved, "#2bc7b4"], ["În așteptare", stats?.pending, "#8d6bda"], ["Semnalate", stats?.flagged, "#e57a87"]].map(([label, value, color]: any) => <div key={label} className="rounded-lg border border-white/6 bg-black/20 p-3 text-[#aaa0ad]">{label}<b className="ml-2" style={{ color }}>{value ?? "—"}</b></div>)}</div><div className="mt-5 space-y-3">{questions.map(question => <div key={question.id || question.text} className="rounded-xl border border-white/7 bg-black/15 p-4"><div className="text-sm text-[#dcd1df]">{question.text}</div><div className="mt-3 flex justify-end gap-2"><button onClick={() => action("Lore aprobat", () => quizRealmApi.adminReviewQuestion(question.id, "APPROVED"))} disabled={!question.id} className="rounded-lg bg-[#2bc7b4]/10 px-3 py-2 text-xs text-[#b7f0e6] disabled:opacity-40"><Check size={13} /></button><button onClick={() => action("Lore respins", () => quizRealmApi.adminReviewQuestion(question.id, "REJECTED"))} disabled={!question.id} className="rounded-lg bg-[#e57a87]/10 px-3 py-2 text-xs text-[#ffb5bf] disabled:opacity-40"><Ban size={13} /></button></div></div>)}</div></div>; }
