import { Link, useLocation } from "wouter";
import { useEffect, useState } from "react";
import { ArrowRight, Eye, Flame, LogIn, Play, Sparkles, Swords, Trophy, Users } from "lucide-react";
import { quizRealmApi } from "@/lib/quizrealm";
import { CornerFiligree, HeraldicAvatar, RealmCrest, RuneDivider, TerritoryMapSvg } from "@/components/MedievalSvg";

const initialStats = [{ label: "Active banners", value: "—", note: "awaiting realm signal", icon: Users }, { label: "Battles today", value: "—", note: "server verified", icon: Trophy }, { label: "Lore mastered", value: "—", note: "server verified", icon: Sparkles }];
const modes = [{ name: "Duo", mark: "1 · 1", copy: "A ritual duel of timing, lore and precise territory strikes.", Icon: Swords, accent: "#8d6bda" }, { name: "Classic", mark: "4 · 8", copy: "A living campaign board where alliances and answers redraw borders.", Icon: Eye, accent: "#e0ba58" }, { name: "Blitz", mark: "90 sec", copy: "A lightning rite. Every second is a province left undefended.", Icon: Flame, accent: "#2bc7b4" }];

export default function Home() {
  const [, navigate] = useLocation();
  const [stats, setStats] = useState(initialStats);
  useEffect(() => { let active = true; const load = () => quizRealmApi.stats().then(data => { if (active) setStats([{ label: "Active banners", value: data.activePlayers.toLocaleString(), note: "live sessions", icon: Users }, { label: "Battles today", value: data.matchesToday.toLocaleString(), note: "recorded by the realm", icon: Trophy }, { label: "Lore mastered", value: data.questionsMastered.toLocaleString(), note: "answers engraved", icon: Sparkles }]); }).catch(() => undefined); load(); const timer = window.setInterval(load, 30_000); return () => { active = false; clearInterval(timer); }; }, []);
  return <div className="realm-surface min-h-screen overflow-hidden"><div className="mx-auto max-w-[1440px] px-5 pb-16 lg:px-10">
    <header className="flex h-24 items-center justify-between"><Link href="/" className="flex items-center gap-3"><RealmCrest className="h-12 w-12 text-[#e3c36a]" /><div><div className="font-display text-base text-[#f7e7b0]">QUIZREALM</div><div className="eyebrow !text-[.5rem]">Arcane tactical archive</div></div></Link><nav className="hidden items-center gap-7 text-xs font-bold uppercase tracking-[.16em] text-[#a69ead] md:flex"><a href="#codex" className="hover:text-[#f5e0a0]">The codex</a><a href="#modes" className="hover:text-[#f5e0a0]">War paths</a><a href="#prestige" className="hover:text-[#f5e0a0]">Hall of sigils</a></nav><button onClick={() => navigate("/auth")} className="sigil-button flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm font-extrabold"><LogIn size={16} /> Enter realm</button></header>
    <section className="grid min-h-[620px] items-center gap-12 py-12 lg:grid-cols-[.98fr_1.02fr] lg:py-20"><div className="animate-rise max-w-2xl"><div className="rune-chip inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-[11px] font-bold uppercase tracking-wider text-[#dfcbff]"><span className="h-1.5 w-1.5 rounded-full bg-[#9bf4e9] shadow-[0_0_12px_#9bf4e9]" /> Chronicle I · The veiled constellation</div><h1 className="mt-7 font-display text-5xl leading-[1.04] text-[#fff2ce] sm:text-6xl lg:text-8xl">Rule the map.<span className="mt-1 block bg-gradient-to-r from-[#fff0bd] via-[#e0ba58] to-[#a66b27] bg-clip-text text-transparent">Master the lore.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#bfb4c3]">A multiplayer knowledge campaign rendered as a living realm. Answer true, seize provinces, and become the strategist whose sigil outlasts the season.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/game" className="sigil-button flex items-center gap-2 rounded-lg px-6 py-3.5 text-sm font-extrabold"><Play size={17} fill="currentColor" /> Begin campaign <ArrowRight size={16} /></Link><button onClick={() => navigate("/auth")} className="rounded-lg border border-[#8d6bda]/45 bg-[#8d6bda]/10 px-6 py-3.5 text-sm font-bold text-[#e8dcff] hover:bg-[#8d6bda]/20">Forge your sigil</button></div><div className="mt-10 flex items-center gap-4"><div className="flex -space-x-3">{(["astromancer", "runeknight", "oracle"] as const).map(variant => <div key={variant} className="h-10 w-10 rounded-full border-2 border-[#11111a] bg-[#14131d]"><HeraldicAvatar variant={variant} className="h-full w-full" /></div>)}</div><div className="text-xs text-[#a89eab]"><b className="text-[#f7e7b0]">{stats[0].value}</b> banners currently raised</div></div></div>
      <div className="relative mx-auto w-full max-w-[660px] animate-rise [animation-delay:120ms]"><div className="absolute -inset-16 bg-[#8d6bda]/15 blur-[100px]" /><div className="engraved-frame relative overflow-hidden rounded-[2rem] p-3"><div className="relative overflow-hidden rounded-[1.55rem] bg-[#0c0b14] p-3"><TerritoryMapSvg className="relative z-10 h-auto w-full drop-shadow-[0_0_30px_rgba(141,107,218,.3)]" /><div className="absolute bottom-5 left-5 right-5 z-20 flex items-center justify-between border border-[#e0ba58]/25 bg-[#0a0b12]/85 px-4 py-3 backdrop-blur-md"><div><div className="eyebrow !text-[.55rem]">Territory pulse</div><div className="mt-1 text-sm font-bold text-[#f7e7b0]">The Astral Frontier</div></div><div className="text-right"><div className="text-[10px] uppercase tracking-widest text-[#9f94a8]">Cycle 04</div><div className="font-display text-sm text-[#e3c36a]">02:14</div></div></div></div></div><div className="panel absolute -bottom-5 -left-4 hidden rounded-xl px-4 py-3 sm:block"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-[#8d6bda]/20 text-[#d6c5ff]"><Swords size={17} /></div><div><div className="text-[10px] uppercase tracking-wider text-[#968b9d]">Province claimed</div><div className="text-sm font-bold text-[#f7e7b0]">Ember Gate</div></div></div></div></div></section>
    <RuneDivider className="h-8 w-full text-[#e0ba58]" /><section className="grid gap-3 py-7 sm:grid-cols-3">{stats.map(({ label, value, note, icon: Icon }) => <div key={label} className="flex items-center gap-4 px-3 py-2"><div className="grid h-11 w-11 place-items-center rounded-xl border border-[#e0ba58]/20 bg-[#e0ba58]/8 text-[#e3c36a]"><Icon size={18} /></div><div><div className="text-2xl font-bold tracking-tight text-[#f7edcf]">{value}</div><div className="text-xs text-[#a59aa7]">{label} <span className="ml-1 text-[#9bf4e9]">{note}</span></div></div></div>)}</section>
    <section id="modes" className="py-20"><div className="mb-9 flex items-end justify-between"><div><div className="eyebrow">War paths</div><h2 className="mt-3 font-display text-3xl text-[#f7e7b0] sm:text-4xl">Choose your campaign.</h2></div><Link href="/game" className="hidden text-sm font-bold text-[#e3c36a] sm:flex sm:items-center sm:gap-2">Open campaign map <ArrowRight size={15} /></Link></div><div className="grid gap-4 md:grid-cols-3">{modes.map(({ name, mark, copy, Icon, accent }) => <Link href="/game" key={name} className="panel panel-hover group relative min-h-64 overflow-hidden rounded-2xl p-6"><CornerFiligree className="absolute -left-3 -top-3 h-24 w-24" style={{ color: accent }} /><CornerFiligree flip className="absolute -bottom-3 -right-3 h-24 w-24" style={{ color: accent }} /><div className="relative flex h-full flex-col justify-between"><div className="flex items-center justify-between"><div className="grid h-12 w-12 place-items-center rounded-xl border border-white/10 bg-black/20" style={{ color: accent }}><Icon size={23} /></div><span className="rune-chip rounded-full px-3 py-1 text-[11px] font-bold text-[#d8cedd]">{mark}</span></div><div><h3 className="font-display text-2xl text-[#f7e7b0]">{name}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-[#aaa0ad]">{copy}</p></div></div></Link>)}</div></section>
    <section id="prestige" className="engraved-frame relative grid gap-8 overflow-hidden rounded-3xl p-8 sm:p-11 lg:grid-cols-[1fr_auto] lg:items-center"><TerritoryMapSvg className="pointer-events-none absolute -right-24 -top-24 h-[340px] w-[620px] opacity-[.1]" /><div className="relative"><div className="eyebrow">Hall of sigils</div><h2 className="mt-3 font-display text-3xl text-[#f7e7b0]">Let every victory become a relic.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-[#aaa0ad]">Build a profile that looks like a captain’s archive: rare achievements, equipped seals, curated chronicles and a prestige score written in gold.</p></div><Link href="/profile" className="relative rounded-lg border border-[#e0ba58]/40 bg-[#e0ba58]/10 px-5 py-3 text-center text-sm font-bold text-[#f5dda0] hover:bg-[#e0ba58]/18">Inspect prestige archive</Link></section>
    <footer className="flex flex-wrap items-center justify-between gap-3 py-12 text-xs text-[#716a76]"><span>© 2026 QuizRealm · The Arcane Archive</span><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#2bc7b4]" /> Realm signal nominal</span></footer>
  </div></div>;
}
