import { useEffect, useMemo, useState } from "react";
import { Crown, Filter, Medal, Search, Shield, Sparkles, Trophy, Users } from "lucide-react";
import { quizRealmApi } from "@/lib/quizrealm";
import { AvatarRuneRing, CornerFiligree, HeraldicAvatar, RuneDivider, TerritoryMapSvg } from "@/components/MedievalSvg";

const fallbackPlayers = [["01", "AstraNoir", "Oracle III", "1,842", "66.1%", "#e0ba58", "astromancer"], ["02", "VelvetRune", "Oracle III", "1,816", "64.8%", "#8d6bda", "oracle"], ["03", "M. Orpheus", "Sage I", "1,791", "63.4%", "#8d6bda", "runeknight"], ["04", "KestrelVoid", "Sage I", "1,764", "61.9%", "#8d6bda", "astromancer"], ["05", "LumenVale", "Scholar II", "1,721", "59.7%", "#2bc7b4", "oracle"], ["06", "Northstar", "Scholar II", "1,694", "58.2%", "#2bc7b4", "runeknight"]] as const;
const tone = (rank: string) => rank.includes("Oracle") ? "#8d6bda" : rank.includes("Sage") ? "#a98fcd" : "#2bc7b4";

export default function Leaderboard() {
  const [tab, setTab] = useState("global"); const [tier, setTier] = useState("Toate treptele"); const [rows, setRows] = useState<any[]>([...fallbackPlayers]); const [synced, setSynced] = useState(false); const [search, setSearch] = useState("");
  useEffect(() => { quizRealmApi.leaderboard("?limit=20").then((payload: any) => { if (!Array.isArray(payload?.entries)) return; setRows(payload.entries.map((entry: any, index: number) => [String(entry.position).padStart(2, "0"), entry.username, entry.rank?.label ?? entry.rank?.name ?? "Scholar", Number(entry.eloRating).toLocaleString(), entry.matchesPlayed ? `${entry.matchesPlayed} meciuri` : "—", tone(entry.rank?.label ?? ""), (["astromancer", "oracle", "runeknight"] as const)[index % 3]])); setSynced(true); }).catch(() => undefined); }, []);
  const visible = useMemo(() => rows.filter(row => (tier === "Toate treptele" || String(row[2]).includes(tier)) && String(row[1]).toLowerCase().includes(search.toLowerCase())), [rows, tier, search]);
  return <div className="realm-surface min-h-[calc(100vh-72px)]"><div className="mx-auto max-w-[1120px] px-5 py-12 lg:px-10"><div className="relative overflow-hidden"><TerritoryMapSvg className="pointer-events-none absolute -right-44 -top-52 h-[560px] w-[900px] opacity-[.11]" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="eyebrow">Marele registru</div><h1 className="mt-3 font-display text-4xl text-[#f7e7b0]">Rangurile tărâmului.</h1><p className="mt-3 text-sm text-[#aaa0ad]">Fiecare poziție se câștigă prin lore, sânge rece și teritoriu cucerit.</p></div><div className="rune-chip flex items-center gap-2 rounded-full px-3 py-2 text-xs text-[#b9f2ea]"><span className="h-1.5 w-1.5 rounded-full bg-[#2bc7b4]" />{synced ? "Registru sincronizat" : "Previzualizare de cronică"}</div></div></div><RuneDivider className="mt-7 h-7 w-full text-[#e0ba58]" />
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-xl border border-[#e0ba58]/15 bg-black/20 p-1">{[["global", "Registrul tărâmului", Trophy], ["friends", "Stindarde aliate", Users]].map(([id, label, Icon]: any) => <button key={id} onClick={() => setTab(id)} className={`flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-bold ${tab === id ? "bg-[#e0ba58]/12 text-[#f5dda0]" : "text-[#998e9d]"}`}><Icon size={15} /> {label}</button>)}</div><div className="flex gap-2"><div className="relative hidden sm:block"><Search size={14} className="absolute left-3 top-3 text-[#a99883]" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Caută un stindard" className="h-9 w-40 rounded-lg border border-[#e0ba58]/15 bg-black/20 pl-9 pr-3 text-xs text-white outline-none focus:border-[#e0ba58]/50" /></div><button onClick={() => setTier(tier === "Toate treptele" ? "Oracle" : "Toate treptele")} className="flex items-center gap-2 rounded-lg border border-[#e0ba58]/15 bg-black/20 px-3 py-2 text-xs text-[#cbc1cf]"><Filter size={14} />{tier}</button></div></div>
    <div className="engraved-frame mt-4 overflow-hidden rounded-2xl"><div className="grid grid-cols-[42px_minmax(0,1fr)_72px] gap-2 border-b border-[#e0ba58]/16 px-5 py-4 text-[10px] uppercase tracking-widest text-[#9c91a0] sm:grid-cols-[72px_1fr_150px_130px_110px]"><span>Sigiliu</span><span>Purtător de stindard</span><span className="hidden sm:block">Ordin</span><span>Renume</span><span className="hidden sm:block">Campanie</span></div>{visible.map(([rank, name, playerTier, elo, record, color, variant], index) => <div key={name} className={`grid grid-cols-[42px_minmax(0,1fr)_72px] items-center gap-2 border-b border-white/6 px-5 py-4 last:border-b-0 sm:grid-cols-[72px_1fr_150px_130px_110px] ${index === 0 ? "bg-[#e0ba58]/[.035]" : ""}`}><div className={`font-display text-lg ${index < 3 ? "text-[#e3c36a]" : "text-[#938895]"}`}>{rank}</div><div className="flex items-center gap-3"><div className="relative h-10 w-10 overflow-hidden rounded-full"><HeraldicAvatar variant={variant} className="h-full w-full" /><AvatarRuneRing className="absolute inset-0 h-full w-full" style={{ color }} />{index === 0 && <Crown size={11} className="absolute -right-1 -top-1 text-[#e3c36a]" />}</div><div><div className="text-sm font-bold text-[#eee4ca]">{name}</div><div className="text-[11px] text-[#8f8494]">{tab === "friends" ? "Stindard aliat" : "Concurent în Sezonul I"}</div></div></div><div className="hidden items-center gap-2 text-xs text-[#d2c4e5] sm:flex"><Shield size={14} style={{ color }} />{playerTier}</div><div className="text-sm font-bold text-[#e3c36a]">{elo}</div><div className="hidden text-sm text-[#b6acba] sm:block">{record}</div></div>)}</div>
    <div className="mt-5 grid gap-4 sm:grid-cols-3">{[[Sparkles, "Stindardul tău", "#148", "Primii 2,4% din tărâm", "#e0ba58"], [Medal, "Următoarea ascensiune", "Oracle II", "58 de renume până la avansare", "#8d6bda"], [Trophy, "Sezonul se închide", "18 zile", "Ține-ți coroana caldă", "#2bc7b4"]].map(([Icon, label, value, note, color]: any) => <div key={label} className="panel relative overflow-hidden rounded-2xl p-5"><CornerFiligree className="absolute -right-6 -top-6 h-20 w-20" style={{ color }} /><div className="relative flex items-center gap-2 text-xs text-[#aaa0ad]"><Icon size={14} style={{ color }} />{label}</div><div className="relative mt-3 font-display text-3xl text-[#f7e7b0]">{value}</div><div className="relative mt-1 text-xs text-[#8f8494]">{note}</div></div>)}</div>
  </div></div>;
}
