import { Link } from "wouter";
import { useEffect, useState } from "react";
import { Award, Crown, Flame, Gem, LockKeyhole, Medal, Shield, Sparkles, Star, Trophy } from "lucide-react";
import { quizRealmApi } from "@/lib/quizrealm";
import { AvatarRuneRing, CornerFiligree, HeraldicAvatar, RuneDivider, TerritoryMapSvg } from "@/components/MedievalSvg";

const achievements = [
  { name: "First Dominion", desc: "Win your first territory match", rarity: "Common", progress: "1 / 1", done: true, color: "#a79773" },
  { name: "Lorekeeper", desc: "Answer 100 questions correctly", rarity: "Rare", progress: "74 / 100", done: false, color: "#8d6bda" },
  { name: "Unbroken Will", desc: "Win 10 matches in a row", rarity: "Epic", progress: "6 / 10", done: false, color: "#2bc7b4" },
  { name: "Grand Cartographer", desc: "Control 100 territories", rarity: "Legendary", progress: "100 / 100", done: true, color: "#e0ba58" },
] as const;

export default function Profile() {
  const [profile, setProfile] = useState<any>(null);
  const [synced, setSynced] = useState(false);
  useEffect(() => { Promise.all([quizRealmApi.profile(), quizRealmApi.achievementSummary()]).then(([data]) => { setProfile(data); setSynced(true); }).catch(() => undefined); }, []);
  const name = profile?.displayName ?? profile?.username ?? "AstraNoir";
  return <div className="realm-surface min-h-[calc(100vh-72px)]"><div className="mx-auto max-w-[1240px] px-5 py-10 lg:px-10">
    <section className="engraved-frame relative overflow-hidden rounded-3xl p-6 sm:p-8"><TerritoryMapSvg className="pointer-events-none absolute -right-44 -top-48 h-[520px] w-[920px] opacity-[.13]" /><CornerFiligree className="absolute -left-3 -top-3 h-28 w-28 text-[#e0ba58]" /><CornerFiligree flip className="absolute -bottom-3 -right-3 h-28 w-28 text-[#8d6bda]" /><div className="relative flex flex-col gap-6 sm:flex-row sm:items-end"><Avatar variant="astromancer" className="h-24 w-24" color="text-[#e0ba58]" /><div className="flex-1"><div className="eyebrow">Astral frontier · member since 2026</div><h1 className="mt-2 font-display text-3xl text-[#f7e7b0]">{name}</h1><p className="mt-2 text-sm text-[#aaa0ad]">Keeper of forgotten constellations · Bucharest, RO</p></div><div className="flex items-center gap-2"><span className="rune-chip rounded-lg px-3 py-2 text-xs font-bold text-[#f5dda0]">ORACLE III</span><span className="rounded-lg border border-[#2bc7b4]/30 bg-[#2bc7b4]/8 px-3 py-2 text-xs font-bold text-[#b5f1e8]">LVL 28</span></div></div></section>
    <RuneDivider className="mt-5 h-7 w-full text-[#e0ba58]" />
    <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
      <section className="space-y-5"><div className="engraved-frame rounded-2xl p-6"><div className="flex items-start justify-between"><div><div className="eyebrow">Prestige archive · {synced ? "server sync" : "chronicle preview"}</div><div className="mt-2 flex items-baseline gap-2"><span className="font-display text-5xl text-[#e3c36a]">{profile?.prestigeScore?.toLocaleString?.() ?? "12,840"}</span><span className="text-xs text-[#938895]">relic score</span></div></div><div className="grid h-12 w-12 place-items-center rounded-xl bg-[#e0ba58]/10 text-[#e3c36a]"><Crown size={22} /></div></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/8"><div className="h-full w-[68%] rounded-full bg-gradient-to-r from-[#8d6bda] via-[#2bc7b4] to-[#e0ba58]" /></div><div className="mt-2 flex justify-between text-[11px] text-[#998e9d]"><span>Next title · High Sage</span><span>68%</span></div></div>
        <div className="panel rounded-2xl p-6"><div className="flex items-center justify-between"><div><div className="eyebrow">Achievement codex</div><h2 className="mt-2 text-xl font-bold text-[#f7e7b0]">Recent relics</h2></div><Link href="/leaderboard" className="text-xs font-bold text-[#e3c36a]">View ranks</Link></div><div className="mt-5 space-y-3">{achievements.map(item => <AchievementRow key={item.name} item={item} />)}</div></div>
      </section>
      <aside className="space-y-5"><div className="engraved-frame rounded-2xl p-6"><div className="flex justify-between"><div><div className="eyebrow">Equipped sigils</div><h2 className="mt-2 text-lg font-bold text-[#f7e7b0]">Banner insignia</h2></div><Shield size={18} className="text-[#e3c36a]" /></div><div className="mt-5 flex gap-3">{[{ Icon: Crown, color: "#e0ba58" }, { Icon: Star, color: "#8d6bda" }, { Icon: Flame, color: "#2bc7b4" }].map(({ Icon, color }) => <div key={color} className="grid h-16 w-16 place-items-center rounded-2xl border" style={{ borderColor: `${color}66`, background: `${color}16`, color }}><Icon size={25} /></div>)}</div><p className="mt-4 text-xs leading-5 text-[#9b90a0]">Three sigils shown beside your banner across the realm.</p></div><div className="panel rounded-2xl p-6"><div className="flex items-center gap-2"><Gem size={17} className="text-[#e3c36a]" /><span className="eyebrow">Curated showcase</span></div><div className="mt-4 grid grid-cols-3 gap-2">{[Award, Trophy, Medal, Sparkles, Crown, Shield].map((Icon, index) => <div key={index} className="grid aspect-square place-items-center rounded-xl border border-[#8d6bda]/25 bg-[#8d6bda]/10 text-[#d3c0ff]"><Icon size={20} /></div>)}</div></div><div className="panel rounded-2xl p-6"><div className="eyebrow">Battle ledger</div><div className="mt-4 grid grid-cols-2 gap-3">{[["Matches", "248"], ["Wins", "164"], ["Win rate", "66.1%"], ["Best streak", "12"]].map(([label, value]) => <div key={label} className="rounded-xl bg-black/20 p-3"><div className="text-xs text-[#998e9d]">{label}</div><div className="mt-1 text-xl font-bold text-[#f7e7b0]">{value}</div></div>)}</div></div></aside>
    </div>
  </div></div>;
}

function AchievementRow({ item }: { item: (typeof achievements)[number] }) { return <div className="flex items-center gap-3 rounded-xl border border-white/6 bg-black/15 p-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl" style={{ background: `${item.color}16`, color: item.color }}>{item.done ? <Award size={18} /> : <LockKeyhole size={16} />}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div className="truncate text-sm font-bold text-[#eee4ca]">{item.name}</div><span className="text-[10px] font-bold uppercase tracking-widest" style={{ color: item.color }}>{item.rarity}</span></div><div className="mt-1 text-xs text-[#9b90a0]">{item.desc}</div><div className="mt-2 h-1 rounded-full bg-white/8"><div className="h-full rounded-full" style={{ width: item.done ? "100%" : item.progress.startsWith("74") ? "74%" : "60%", background: item.color }} /></div></div><span className="text-[10px] text-[#938895]">{item.progress}</span></div>; }
function Avatar({ variant, color, className }: { variant: "astromancer" | "runeknight" | "oracle"; color: string; className: string }) { return <div className={`relative shrink-0 overflow-hidden rounded-full ${className}`}><HeraldicAvatar variant={variant} className="h-full w-full" /><AvatarRuneRing className={`absolute inset-0 h-full w-full ${color}`} /></div>; }
